### ISSUE TITLE
How to use audio files aligned with tracked mesh？

### ISSUE THREAD

**Issue by ChenWang8750** [facebookresearch/multiface#31]
Thanks for your excellent work!
What does the name of audio file mean? And how to align with the tracked mesh files?

**Comment by alexanderrichard** [comment]
Hi,
the audio files are named after the sentences the participants were saying. They all start with SEN (for "sentence") and then have the words spoken in that sentence in the filename (for example "A good morrow to you, my boy").

They are cut so that they fit the sequence length of the tracked meshes. So, if you concatenate all tracked meshes of a sentence (which are at 30fps) in numerical order, the audio will have the same duration as that sequence. In other words, every 1600 samples from the audio file (48kHz) correspond to a frame.
