### ISSUE TITLE
Can I specify the cameras during downloading?

### ISSUE THREAD

**Issue by chenerg** [facebookresearch/multiface#7]
The size of all images from all cameras is too large to download? Can I only download a subset of camera images?

**Comment by cwuu** [comment]
Hi, 

No, you won't be able to specify the specific cameras to be downloaded since some of the .tar files for image asset is grouped by the level of expression. We did not provide the finer level of grouping for grouping by camera. You may refer to the [data structure](https://github.com/facebookresearch/multiface/blob/main/documentation/DATA_STRUCTURE.md) documentation to get some details. Thanks.
